version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    volumes:
      - "./data/redis:/data"
    expose:
      - ${REDIS_PORT}
  server:
    container_name: label-studio-ml
    build: .
    env_file:
      - .env
    environment:
      - RQ_QUEUE_NAME=default
      - REDIS_HOST=redis
      - LABEL_STUDIO_USE_REDIS=true
    ports:
      - ${BACKEND_PORT}:9090
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - "./weights:/data"
      - "./logs:/tmp"
